name: build
on:
  push:
  pull_request:
  schedule:
    - cron: 0 23 * * *
jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      GOPATH: /home/runner/work/terrascan
      GOBIN: /home/runner/work/terrascan/bin
      GO_VERSION: 1.17
    steps:
    - name: Checkout Terrascan
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build Terrascan docker image
      run: make docker-build && docker images
      
    - name: wget
      uses: wei/wget@v1
      with:
        args: -O tcs.tar.gz https://staging.tenable.com/downloads/api/v2/pages/tenable-cs/files/tenable.cs-cli-linux-v2.0.0.tar.gz
        
    - name: extract
      run: tar -xf tcs.tar.gz tcs && rm tcs.tar.gz && install tcs /usr/local/bin
      
    - name: tcs version
      run: tcs version

    - name: tcs image scan
      run: tcs scan -t=container-image --image=docker-daemon:tenable/terrascan:${{ env.TERRASCAN_TAG }} --appurl=https://qa-develop.cloud.aws.tenablesecurity.com/cns --token=${{ secrets.TIO_API_TOKEN }} --repo-name=https://github.com/nasir-rabbani/terrascan --project=b977ea79-e552-43a3-a6f6-fd300427d09c -l debug
